modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
    modId="husbandry"
    version="${file.jarVersion}"
    displayName="Husbandry"
    authors="joshiejack"
    description='''Take care of your animals for more rewards.'''
[[dependencies.husbandry]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.husbandry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.husbandry]]
    modId="penguinlib"
    mandatory=true
    versionRange="[0.3.1,)"
    ordering="NONE"
    side="BOTH"